### ISSUE TITLE
instagram-py command not found

### ISSUE THREAD

**Issue by brianmituka** [deathsec/instagram-py#1]
when i run `instagram-py` I get `command not found`. How can I get it to run

**Comment by deathsec** [comment]
Hi , @brianmituka you have to run 

```
 $ sudo python3 setup.py install # in the cloned instagram-py folder!
```

[See the installation section for complete guide on Installation!](https://github.com/deathsec/instagram-py#installation)

Thank you for reporting!

**Comment by deathsec** [comment]
and @brianmituka could you mention your operating system and how you installed instagram-py , any way that i can use to reproduce this error , will be very useful

**Comment by brianmituka** [comment]
my operating system is linux mint cinnamon. I used the instructions in the README file

**Comment by deathsec** [comment]
Did you try running it now , does it work?

**Comment by deathsec** [comment]
@brianmituka The installation looks good , I think i found the bug!   
Can please post the output of the command bellow

```
 $ python --version
```

**Comment by brianmituka** [comment]
@deathsec the output is `Python 2.7.12` . I have two  versions of python

**Comment by brianmituka** [comment]
@deathsec I have changed the default to 3.5.2 and run `sudo python3 setup.py install`. but still command not found I am running linux mint cinnamon 32bit version 18.1 serena. I had not given you a detailed info about my os

**Comment by deathsec** [comment]
@brianmituka i will look into it now , i will check myself on linux mint live boot , thank you for waiting.
But if you want a quick work around try this.

```
 $ cd path/to/Instagram-Py-That-you-cloned
 $ cp bin/instagram-py .
 $ ./instagram-py 
```
The above only runs when you are inside the dir , so test the tool if you want i will come up with a solution to mint users soon!

**Comment by firebreed** [comment]
I think I have quite a similar issue:

```
sudo python3 setup.py installTraceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import Command, find_packages, setup
ModuleNotFoundError: No module named 'setuptools'
```
Running Python 3.6.0 and also have 2.7.12 just like brianmituka.
Setuptools is installed. Kali Linux rolling.

**Comment by deathsec** [comment]
hey @firebreed thank you for reporting , you should install the dependencies for python setup first its the basic thing to do

```
 $ sudo apt-get update # these are system routine that you have to do every now and then!
 $ sudo apt-get upgrade 
 $ sudo apt-get install python3-setuptools
 $ sudo easy_install3 pip
 $ sudo pip3 install requests --upgrade
 $ sudo pip3 install requests[socks]
 $ sudo pip3 install stem
 $ sudo pip3 install instagram-py # install my app now!
 $ instagram-py # installed

```

**Comment by deathsec** [comment]
Hey @brianmituka  i got it working under linux mint on live boot ( version 18.1).

This is what i did

```
 $ sudo apt-get install python3-setuptools # do update and upgrade your system
 $ sudo easy_install3 -U pip # if you have pip installed! else avoid the -U 
 $ sudo pip3 install requests --upgrade
 $ sudo pip3 install requests[socks]
 $ sudo pip3 install stem
 $ sudo pip3 install instagram-py # install my app now!
```

**Comment by deathsec** [comment]
hey @firebreed , please refer to the installation section without reading it you cannot do anything the configuration is little complicated because its the real thing!

[See the installation section please](https://github.com/deathsec/instagram-py#installation)

**Comment by firebreed** [comment]
> $ sudo apt-get update # these are system routine that you have to do every now and then!
 $ sudo apt-get upgrade 
 $ sudo apt-get install python3-setuptools
 $ sudo easy_install3 pip
 $ sudo pip3 install requests --upgrade
 $ sudo pip3 install requests[socks]
 $ sudo pip3 install stem
 $ sudo pip3 install instagram-py # install my app now!
 $ instagram-py # installed

That did it. I'll try out Instagram-py tomorrow morning. Thanks a bunch.

**Comment by deathsec** [comment]
Thank you @firebreed  , I'm happy that worked for you!

**Comment by deathsec** [comment]
Hey @brianmituka , if you want a very stable and fast solution then execute this one command and nothing else , I made this just for you -> its precompiled to run under any 32 bit linux os! 

```
 $ sudo wget -O /usr/local/bin/instagram-py "https://github.com/deathsec/instagram-py/releases/download/0.3.1/instagram-py32bit"
 $ instagram-py # successfully installed 
```

Simple right ?...

**Comment by deathsec** [comment]
Hi @brianmituka i think the issue is solved please refer to the new installation method in README! , if that did not work please report again...
