### ISSUE TITLE
SOCKS Error

### ISSUE THREAD

**Issue by yellow** [deathsec/instagram-py#10]
`
    instagrampy.TryPassword()
  File "/usr/local/lib/python3.4/dist-packages/InstagramPy/InstagramPyInstance.py", line 134, in TryPassword
    self.session.ChangeIPAddress() # signal tor to change ip
  File "/usr/local/lib/python3.4/dist-packages/InstagramPy/InstagramPySession.py", line 246, in ChangeIPAddress
    self.ip = self.bot.get('https://icanhazip.com').content.rstrip().decode()
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f37a4b01c50>: Failed to establish a new connection: 0x01: General SOCKS server failure',))
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='icanhazip.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f37a4b01c50>: Failed to establish a new connection: 0x01: General SOCKS server failure',))
`

**Comment by yellow** [comment]
After this error tor doesn't work and needs a restart.

**Comment by deathsec** [comment]
anyways to reproduce this might be very helpful ?

**Comment by yellow** [comment]
I was probably running multiple sessions at that time. I'll keep you updated when I encounter that error.

**Comment by deathsec** [comment]
I think I found the problem , this software is not supported to run with multiple instance

**Comment by deathsec** [comment]
Imagine the first instance will request tor to change identity while the other instance is trying a password the situation will end up in a unpredictable situation.

**Comment by deathsec** [comment]
If you can mention what you are aiming for I will redesign it in the next release!

**Comment by yellow** [comment]
One more error.
`fatal error:: unable to send request to instagram :: SOCKSHTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/login/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:600)'),))`

**Comment by deathsec** [comment]
hmm... I am working on this please wait

**Comment by deathsec** [comment]
I suppose this issue is not required as the other one is the one and the same.
