### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by yellow** [deathsec/instagram-py#14]
**Select your issue type:** (check at least one)
- [x] Bug
- [X] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

I'm running this script with these settings on my account.
`instagram-py --username xyz --password-list test -vvv`

I got the following response.

`b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/ABC/XYZ/", "api_path": "/challenge/ABC/XYZ/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}'`

I went to the following URL:
https://i.instagram.com/challenge/ABC/XYZ/
They asked me if I wanted to send an email to x****@y***.com or send message to a number.

But when I tried to use the forgot password functionality, it says that the email is a****@b****.org

P.S: Thanks for all the work you put into this. Making the world a better place!

**Comment by deathsec** [comment]
its not a bug , its the right password but it requires you to verify if thats the real user because of the previous tries , a kind of lock system but trust me if the real user logs in again he/she is going to do the challenge so we just have wait till then , anyways i will verify it again!

**Comment by deathsec** [comment]
Even my fake Instagram Account used to test , **@instatestgod__** will get locked but if a real user logs in again the challenge is gonna disappear and you can use the cracked password again

**Comment by yellow** [comment]
But does the challenge email match with the real email?

**Comment by deathsec** [comment]
I Have no idea about that

**Comment by deathsec** [comment]
I will get it tested with all possible security options in instagram

**Comment by deathsec** [comment]
did you by chance try Instagram-Py Scripting , is it working okay?

**Comment by deathsec** [comment]
I Suppose my fake account got deleted! , I am creating a new one , I seriously never knew about this

**Comment by deathsec** [comment]
On the way I found a another big error I need to patch this its breaking the entire software!

**Comment by deathsec** [comment]
Hey @yellow just found out the script runs smooth so far and does not produce false positives , **it also returns the mobile number and location if we successfully crack the account with the username and password but challenge required accounts does not show it but you can run it later with a single password , will be adding more features soon

Currently Testing it With 200 Password Tries!

**Comment by deathsec** [comment]
Hey @yellow the scripts seems to work just fine but there are some small errors needs to be patched later , not fatal. The thing is after attack finished successfully wait a few minutes may be 30 Mins? , then use a VPN to use the ip of the victims location like America , Japan or So then try logging in with your cracked password 

**The Account Needs to Be Logged Out , Try When the Victim is Offline?**
