### ISSUE TITLE
Thanks for good jub

### ISSUE THREAD

**Issue by mehranexpert** [deathsec/instagram-py#15]
just two question , is it need Proxy ? and second is it block accounts ?

**Comment by deathsec** [comment]
**Answer I**: 
It does not use third party proxies like you used to do in instaBrute , The proxies are automatically managed locally by a seperate program called **Tor** which is also known as the **deep web router** or **The Onion Network** , you will need to open control port for the Tor Server which is mentioned in README. If you have no Idea of Tor then you must  refer the link https://en.wikipedia.org/wiki/The_Tor_Project%2C_Inc

**For Installation and Documentation for Tor Server** - https://www.torproject.org/
**or google how to install tor and open control port for your os**

**Answer II**:
Yes after a long password tries it does block the account **but Instagram-Py will tell you if its a correct Password** So after the attack as finished wait for 30 mins or so and use a VPN to the location of the victims account and then login to instagram with the cracked password and username.

For More Information on this issue look at Issue #14 

Thank You  , And Make Sure to use the Issue Template next time.
