### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by zMaadz** [deathsec/instagram-py#17]
![debian 7-2017-11-20-16-33-40](https://user-images.githubusercontent.com/32825385/33024004-8970efec-ce12-11e7-8794-8026fc4b8acb.png)
i have this issue idk its because that the python version is 2.7 ?
and how i can run this tool on another version of py ? i have 2.7 , 3.4 , 3.5 , 3.6

excuse my english :s

**Comment by deathsec** [comment]
currently only supported with python3.6 , 3.4 , you need to upgrade to v2.0.0 with 
```
$ sudo pip3 install instagram-py # install
$ sudo pip3 install instagram-py --upgrade # update!
```
