### ISSUE TITLE
i can't see changes

### ISSUE THREAD

**Issue by Mehran** [deathsec/instagram-py#18]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
after i change something on `InstagramPyCLI.py` then run `python3 setup.py install` success done . 
but when i run script my change not applied , how can i apply changes ?

**Comment by deathsec** [comment]
if you want to modify and test the source locally then , use this method 
```
 $ cd path/to/instagram-py
 $ # Modify Source files
 $ cp bin/instagram-py .
 $ ./instagram-py # Test it out
```

**Comment by deathsec** [comment]
I have no idea why ``` python3 setup.py install ``` did not work but using the method I mentioned you can use or test your modified version of instagram-py locally , I think you need to uninstall my version with pip. 
Instagram-Py only runs with version 3.6 and 3.4

**Comment by Mehran** [comment]
Thanks for your mentioned , but i wonder why changes not work i also delete `InstagramPyCLI.py` and run script from bin Folder and it run success ,
