### ISSUE TITLE
Proxy Help

### ISSUE THREAD

**Issue by dsama123kl1l3k2** [deathsec/instagram-py#22]
I'm receiving a "Connection to host failed , check your connection and tor configuration." when trying to run my program.

My Tor torrc file says this 

`# This file was generated by Tor; if you edit it, comments will not be preserved
#The old torrc file was renamed to torrc.orig.1 or similar, and Tor will ignore it

ControlPort 9051
DataDirectory /Users/Library/Application Support/TorBrowser-Data/Tor
GeoIPFile /Applications/TorBrowser.app/Contents/Resources/TorBrowser/Tor/geoip
GeoIPv6File /Applications/TorBrowser.app/Contents/Resources/TorBrowser/Tor/geoip6
HashedControlPassword 16: (SNIP)
`

Thank you if you can help!

**Comment by deathsec** [comment]
Do you use password for tor control port ?

**Comment by dsama123kl1l3k2** [comment]
Not sure what you mean by that, sorry.

**Comment by deathsec** [comment]
```
#HashedControlPassword 16
#CookieAuthentication 1
```
You May want to comment this out in the torrc file , and try again!

**Comment by deathsec** [comment]
**And Make sure to run ``` instagram-py -cc ``` once to write configuration automatically.**

**Comment by dsama123kl1l3k2** [comment]
Still receive the same error, sorry for the bother.

**Comment by deathsec** [comment]
did you start the tor server ?

**Comment by deathsec** [comment]
**Note**: This software does not need tor browser , it only requires tor server which is a cli program.
if you are doing this  with the tor browser, please undo all the changes you have made and install tor server.
if you are in windows , then sorry , I don't think you will be able to do hacking with windows.

**Comment by dsama123kl1l3k2** [comment]
I'm so sorry, I'm using a mac, I have been using Tor browser like you have said because I haven't see any information on install tor server.

**Comment by deathsec** [comment]
Sorry I don't think 'The Tor Project' offers a seperate tor server for MacOSX , check this post https://maymay.net/blog/2013/02/20/howto-use-tor-for-all-network-traffic-by-default-on-mac-os-x/ 

Instagram-Py Requires a Tor Control Port which Tor Browser reserves it and we cannot use it by default settings!

**I am really sorry , but there must be a way to configure tor control port in mac , Since I don't own a mac I can't really help you..**

**Comment by dsama123kl1l3k2** [comment]
Are there any other programs you can possibly direct me to?

**Comment by dsama123kl1l3k2** [comment]
Or is there a different way you can possibly update it to use a different proxy system other then tor

**Comment by deathsec** [comment]
Tor is an open source project and you can do anything you like with tor , tor is simply not a proxy , It actually encrypts your packets from your ISP which is safe in our cause..

**Besides doing this stuff is only legal in Tor Server , doing this with free proxy is a pain and thats totally illegal**

**You don't want to get into jail , right?..**

**Comment by deathsec** [comment]
You May want to try this method,
```
ControlPort is generally port 9151. If you go to the browser directory, go under Data, then under Tor, look for the torrc-defaults file. It will say something like
```
ControlPort 9151

then use Instagram-Py to set the configuration , with ``` instagram-py -cc ```.

**Comment by deathsec** [comment]
don't forget to start you tor browser!!

**Comment by dsama123kl1l3k2** [comment]
Sadly, I tried that and it doesn't work. I hope you figure out one day another method, you have a great program and it would be amazing to use it. Thank you for your support!

**Comment by dsama123kl1l3k2** [comment]
Sorry, last question, I came here from the other brute forcer called InstaBrute.py. How are they able to do their job without a tor browser. Are you able to implement the same thing, maybe even an option.

**Comment by deathsec** [comment]
hmm... it used a very un-wise method which used a library called selenum which controls any browser to do whatever like a human do ( Which is very slow and painful , its literally like a human typing and clicking the login button) but this script **mimics the instagram android app** ( which is controlled by the **official instagram api** , I simply found a hole in the api ). do not worry I will find a way to manipulate the tor bundle!

**Comment by dsama123kl1l3k2** [comment]
Thank you! Hope to hear from you soon!

**Comment by deathsec** [comment]
@dsama123kl1l3k2 please see the README again!
