### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by venitmyDNA** [deathsec/instagram-py#3]
i get this eror message, how to fix it?

root@toothless:~# instagram-py andrewxxxx /root/instagram.txt
Instagram-py v0.3.1,  Simple Instagram brute force attacker script
Copyright (C) 2017 The Future Shell , DeathSec

[                          ] [+] got cookie:: f0tTJOUkNxTPO2I98phL2SKyVffDn4eO 

[!] attack started: 2017-09-14 14:17:44.730515
[+] target account: andrewxxxx
[*] password list path: /root/instagram.txt
[ ATTACK STATUS ]
[                          ] [*] Trying... andrew5162                         Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 11, in <module>
    load_entry_point('instagram-py==0.3.1', 'console_scripts', 'instagram-py')()
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/__init__.py", line 89, in main
    InjectPassword(current_session , current_line)
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/instagram_bot.py", line 73, in InjectPassword
    message = json.loads(r.content);
  File "/usr/lib/python3.5/json/__init__.py", line 314, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by deathsec** [comment]
@venitmyDNA I think the version you using is old , please use the latest version instagram-py v0.3.2 
see the installation section for more details

```
 $ sudo easy_install3 -U pip # upgrade pip3 , you should have python3-setuptools
 $ sudo pip3 install requests --upgrade # we need v2.18.x 
 $ sudo pip3 install requests[socks] # for tor
 $ sudo pip3 install stem # tor official library to control tor!
 $ sudo pip3 install instagram-py --upgrade # install or upgrade my app
 $ instagram-py # installed successfully!
```
