### ISSUE TITLE
Tor config : no passphrase provided

### ISSUE THREAD

**Issue by botis0** [deathsec/instagram-py#31]
Keep getting: 
Tor configuration invalid or server down :: no passphrase provided

**Comment by Lias-e** [comment]
have the same issue 
after i got tis error " Tor configuration invalid or server down :: [Errno 111] Connection refused" 
i started tor and so the error message changed to " Tor configuration invalid or server down :: no passphrase provided"
any advice?

**Comment by RanChoU420** [comment]
I wish there was answers for this but I just cant find these, you guys still stuck?
