### ISSUE TITLE
connection to host failed

### ISSUE THREAD

**Issue by zMaadz** [deathsec/instagram-py#4]
- [x] Bug
i have this prob
i tried to manual configuration and the default one.
what i can do ?

![kalii light-2017-12-05-21-35-14](https://user-images.githubusercontent.com/32825385/33626963-26a8530a-d9ca-11e7-9734-de8cf3a74027.png)

**Comment by antony-jr** [comment]
I'm pretty sure that this project is dead! Sorry...

**Comment by antony-jr** [comment]
@zMaadz have you installed tor server ?

**Comment by antony-jr** [comment]
@zMaadz Please do not use this issue tracker , this is not me. This is just a fork , head to https://github.com/antony-jr/instagram-py for the real one.

**Comment by TristonStuart** [comment]
I get same error. @zMaadz Dont listen to @antony-jr He is a fake.

**Comment by antony-jr** [comment]
Please see this , To verify this is the fake account! https://github.com/antony-jr/instagram-py/issues/2

**Comment by amauryleproux** [comment]
@zMaadz @TristonStuart hi guys did you solve your issue? cause i got the same :/

**Comment by antony-jr** [comment]
@amauryleproux what operating system are you using ? Do you have TOR Server Up and running ? ( Not TOR Browser ). If you are in windows then you probabilly can't get it to work. What version of python are you using ? Instagram-Py only works with 3xx.

**Comment by amauryleproux** [comment]
thanks @antony-jr I'm on IOS and I've got python3 .
So I need to setup a TOR server :)

**Comment by antony-jr** [comment]
Sorry @amauryleproux but Only linux is supported. You should do this in a computer , Try **live booting** kali linux.

**Comment by adarmawan26** [comment]
@zMaadz Have you found the solution broo?

**Comment by antony-jr** [comment]
**CC** : @bonds07 , @amauryleproux  , @zMaadz 

These are reasons why this error occurs... , 
* Network Error ( No Internet and other stuff ).
* Tor **server** is not running or not active ( **Tor server is only available on Linux** ).
* Not openning the **Tor Control** Port. 
* Faulty Tor Configuration in Instagram-Py.
* Faulty installation.

Here is a great example on youtube to use instagram-py -> https://www.youtube.com/watch?v=KZEcFn3Z5L0 

**Follow just as the video** , he just took my words into the video.

**Comment by adarmawan26** [comment]
I think, U just need to restart the tor service.

**Comment by antony-jr** [comment]
@bonds07 if it worked then its not a problem! 👍

**Comment by djakaw** [comment]
Hello, i got this issue. 
Connection to host failed , check your connection and tor configuration :: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fd682fa4b70>: Failed to establish a new connection: 0x06: TTL expired',))

![1](https://user-images.githubusercontent.com/16527780/37699907-2d320518-2d1c-11e8-97bb-467cc9b88b78.png)

**Comment by antony-jr** [comment]
@djakaw Please use the official repo , here -> https://github.com/antony-jr/instagram-py

**Comment by Har0ldf1nch** [comment]
If your config file is good, just install requests[socks] with pip3.
And than restart the tor service. It will work.

**Comment by amirovo** [comment]
@djakaw did you fixed it? 
@Har0ldf1nch nstall requests[socks] with pip3 did not work for me

**Comment by cloner494** [comment]
> Hello, i got this issue.
> Connection to host failed , check your connection and tor configuration :: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fd682fa4b70>: Failed to establish a new connection: 0x06: TTL expired',))
> 
> ![1](https://user-images.githubusercontent.com/16527780/37699907-2d320518-2d1c-11e8-97bb-467cc9b88b78.png)

hi so I have the same issues pleas help

**Comment by cloner494** [comment]
> If your config file is good, just install requests[socks] with pip3.
> And than restart the tor service. It will work.

I do this but not work
