### ISSUE TITLE
_

### ISSUE THREAD

**Issue by quote591** [deathsec/instagram-py#43]

**Comment by dark552** [comment]
What did you do for - -create-configuration because that didn’t work for me. If you can help me with that I might be able to help you with your problem.

**Comment by Quote121** [comment]
> What did you do for - -create-configuration because that didn’t work for me. If you can help me with that I might be able to help you with your problem.

instagram-py --create-configuration --default-configuration

Just the default

**Comment by dark552** [comment]
What did you do for cd /root because for me it says permission denied?

**Comment by dark552** [comment]
What did you do for /root$ ls?

**Comment by Quote121** [comment]
> What did you do for /root$ ls?

Not sure what you mean by that, maybe attach a picture
If you cant access /root run as su

e.g. sudo cd /root

**Comment by dark552** [comment]
Go to 3:09 in the video. He does /root$ ls. I tried it and it said no such file or directory.

**Comment by Quote121** [comment]
> Go to 3:09 in the video. He does /root$ ls. I tried it and it said no such file or directory.

What video?

**Comment by Quote121** [comment]
> Go to 3:09 in the video. He does /root$ ls. I tried it and it said no such file or directory.

/root is a directory 
ls is the command to list files in that directory

**Comment by dark552** [comment]
https://youtu.be/KZEcFn3Z5L0

**Comment by Quote121** [comment]
![Annotation 2020-06-07 184753](https://user-images.githubusercontent.com/51723488/83976054-6eee9100-a8ef-11ea-8bd5-37755a349060.png)

The white text is the user input

**Comment by dark552** [comment]
I typed in sudo nano /etc/tor/torcc and it went to the screen but there’s no text.

**Comment by Ifoegbu1** [comment]
> I typed in sudo nano /etc/tor/torcc and it went to the screen but there’s no text.

Yeah copy everything from torrc.orgin and paste in torrc
.... Then uncomment the #ControlPort(that is remove the # before it)

**Comment by Quote121** [comment]
Sorry for people who have tried to help with this issue, turns out it was my router setting denying the tor services from working properly.
