### ISSUE TITLE
I need help with finding proxy tor IP

### ISSUE THREAD

**Issue by Fadi2003** [deathsec/instagram-py#5]
For the config changing part I got confused because I don't know what or where to find an available IP and port so would you please be nice enough to help me with that, thank you so much for making such an awsome script I hope that you're having a great day. And also thank you for reading my Issue.

**Comment by Fadi2003** [comment]
Can I include more than one IP and port?

**Comment by Fadi2003** [comment]
![screenshot from 2017-10-15 00-40-51](https://user-images.githubusercontent.com/29684241/31582775-48876bbc-b17c-11e7-8270-4bfa21c117f6.png)

**Comment by Fadi2003** [comment]
i keep getting this for some reason

**Comment by deathsec** [comment]
@Fadi2003 I Will look into it soon , It seems that its my bad..

**Comment by deathsec** [comment]
@Fadi2003 I Found your error , you are excuting Instagram-py from python2.7 which is not supported currently! 
```
 $ cat /usr/bin/instagram-py
```

@Fadi2003 could you please post the output of the above command?

**Comment by deathsec** [comment]
**For the proxy part** , you do not need to change anything but you just have to setup **tor server and open tor control port** refer **tor documentation**.

**Comment by deathsec** [comment]
issue as been closed for delay in response , re-open if you want any help!
