### ISSUE TITLE
How do i save the vim file in the terminal?

### ISSUE THREAD

**Issue by ColeShelly** [deathsec/instagram-py#6]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

## controller applications, as documented in control-spec.txt
#ControlPort 9051

~ So I Uncommented the # before the ControlPort, but I don't know how to save it.. Please Help

**Ways to Reproduce the issue (optional):**

**Comment by Har0ldf1nch** [comment]
Open it with gedit and CTRL+S. Change vim --> gedit in code.
