### ISSUE TITLE
What do you mean with this: make sure your tor configuration matched ~/instapy-config.json

### ISSUE THREAD

**Issue by NuBHaze** [deathsec/instagram-py#6]
Hi, I red your 'README' file, but I still don't know what to do with the tor inside /instapy-config.jsor.
Is there any way you can help me?
The Installation proces went fine, just don't understand what to do with tor.
Also already uncommented Controlport 0951 but still no clue what to do.

{
 "api-url" : "https://i.instagram.com/api/v1/",
 "user-agent" : "Instagram 10.26.0 Android (18/4.3; 320dp..... ",
 "ig-sig-key" : "4f8732eb9ba7d1c8e8897a75d6474d4eb3f5279137431b2aafb71fafe2abe178",
 "ig-sig-version" : "4",
 "tor" : { WHAT DO I NEED TO INSERT HERE?
    "server" : "127.0.0.1",
    "port" : "9050",
    "protocol" : "socks5",
    "control" : {
          "password" : "",
          "port" : "9051"
      }
  }

}

Ps: sorry for my bad english, and I'm a noob regarding python and Linux.

**Comment by deathsec** [comment]
Do you have tor server up and running , enabled the control port?

**Comment by deathsec** [comment]
you don't need to write your own configuration download it from the repo to your home folder , if you use tor default settings you don't even have to touch the configuration

**Comment by NuBHaze** [comment]
I appreciate your quick response! Thanks
