### ISSUE TITLE
Support for multiple instances

### ISSUE THREAD

**Issue by yellow** [deathsec/instagram-py#9]
I think it can be done by adding multiple SOCKSPort to the torrc config file.
But it would probably require multiple instapy-config.json files to work.

**Comment by deathsec** [comment]
why you need to run multiple instances of Instagram-Py , attacking more users ?
Because creating multiple configuration is not good  , if you can mention what you are aiming for I can redesign the software on the next release ?

**Comment by yellow** [comment]
Yes. I want to try to brute-force the passwords for all my accounts.

**Comment by deathsec** [comment]
in that case the release is estimated within the next 24 hrs so please wait till then

**Comment by yellow** [comment]
Thanks very much!

**Comment by deathsec** [comment]
I suppose the next release will take a little more time , Sorry 
But the next release is packed with amazing features...

* Instagram-Py Scripts
Create your own attack scripts with a lot of customization that includes multiple username attack
with a lot of configuration for each username

* Improved CLI
The Command Line will be improved

* More Bug fixes 

Please wait a little... as this is a new feature

**Comment by yellow** [comment]
Thanks very much!

**Comment by deathsec** [comment]
@yellow This issue is solved in **v2.0.0** ,
**Upgrade your Instagram-Py with pip3**

```
 $ sudo pip3 install instagram-py --upgrade
```
You Need to use **Instagram-Py Scripting** to solve this issue , see the README.

refer here to know more about attack on multiple usernames https://github.com/deathsec/instagram-py/tree/v2.0.0/examples
